# Generated by Django 4.1.7 on 2023-02-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField(max_length=30)),
                ('PhoneNumber', models.CharField(default=False, max_length=10, unique=True)),
                ('EmailID', models.EmailField(default=False, max_length=100, unique=True)),
            ],
        ),
    ]
